In [2]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

#For Data Viz. 
import matplotlib.pyplot as plt
import seaborn as sns 

#For Warnings
import warnings
warnings.filterwarnings('ignore')

#For Options 
pd.set_option('display.max_columns' , None)
pd.set_option('display.max_rows', None)

<b> Look for insights <br> 
   1.Finding out how many of each type and breed of dog are brought into shelters across the USA in a given year. <br>
   2.Seeing which states have the most imports of dogs and what breeds/types those are. <br>
   3.Determining if there are any trends in the types/breeds of dogs being brought into shelters (e.g. more pit bulls than golden retrievers) <br>

In [3]:
dog_travel = "/Users/linfangqing/Desktop/dog_adopt/dogTravel.csv"
dog_description = "/Users/linfangqing/Desktop/dog_adopt/allDogDescriptions.csv"
moves_by_location = "/Users/linfangqing/Desktop/dog_adopt/movesByLocation.csv"

In [4]:
dog_travel_df = pd.read_csv(dog_travel)
dog_desc_df = pd.read_csv(dog_description)
moves_by_loc_df = pd.read_csv(moves_by_location)

In [5]:
dog_travel_df.head()

,index,id,contact_city,contact_state,description,found,manual,remove,still_there
0,0,44520267,Anoka,MN,Boris is a handsome mini schnauzer who made hi...,Arkansas,NaN,NaN,NaN
1,1,44698509,Groveland,FL,Duke is an almost 2 year old Potcake from Abac...,Abacos,Bahamas,NaN,NaN
2,2,45983838,Adamstown,MD,Zac Woof-ron is a heartthrob movie star lookin...,Adam,Maryland,NaN,NaN
3,3,44475904,Saint Cloud,MN,~~Came in to the shelter as a transfer from an...,Adaptil,NaN,True,NaN
4,4,43877389,Pueblo,CO,Palang is such a sweetheart. She loves her peo...,Afghanistan,NaN,NaN,NaN

In [6]:
moves_by_loc_df.head()

   index        location  exported  imported   total  inUS
0      0           Texas     635.0       NaN   566.0  True
1      1         Alabama     268.0       2.0  1428.0  True
2      2  North Carolina     158.0      14.0  2627.0  True
3      3  South Carolina     139.0      12.0  1618.0  True
4      4         Georgia     137.0      19.0  3479.0  True

In [7]:
dog_desc_df.head()

,index,id,org_id,url,type.x,species,breed_primary,breed_secondary,breed_mixed,breed_unknown,color_primary,color_secondary,color_tertiary,age,sex,size,coat,fixed,house_trained,declawed,special_needs,shots_current,env_children,env_dogs,env_cats,name,status,posted,contact_city,contact_state,contact_zip,contact_country,stateQ,accessed,type.y,description
0,0,46042150,NV163,https://www.petfinder.com/dog/harley-46042150/...,Dog,Dog,American Staffordshire Terrier,Mixed Breed,True,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,HARLEY,adoptable,2019-09-20T16:37:59+0000,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,Harley is not sure how he wound up at shelter ...
1,1,46042002,NV163,https://www.petfinder.com/dog/biggie-46042002/...,Dog,Dog,Pit Bull Terrier,Mixed Breed,True,False,Brown / Chocolate,White / Cream,NaN,Adult,Male,Large,Short,True,True,NaN,False,True,NaN,NaN,NaN,BIGGIE,adoptable,2019-09-20T16:24:57+0000,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,6 year old Biggie has lost his home and really...
2,2,46040898,NV99,https://www.petfinder.com/dog/ziggy-46040898/n...,Dog,Dog,Shepherd,NaN,False,False,Brindle,NaN,NaN,Adult,Male,Large,Short,True,False,NaN,False,True,NaN,NaN,NaN,Ziggy,adoptable,2019-09-20T14:10:11+0000,Mesquite,NV,89027,US,89009,2019-09-20,Dog,Approx 2 years old.\n Did I catch your eye? I ...
3,3,46039877,NV202,https://www.petfinder.com/dog/gypsy-46039877/n...,Dog,Dog,German Shepherd Dog,NaN,False,False,NaN,NaN,NaN,Baby,Female,Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,Gypsy,adoptable,2019-09-20T10:08:22+0000,Pahrump,NV,89048,US,89009,2019-09-20,Dog,NaN
4,4,46039306,NV184,https://www.petfinder.com/dog/theo-46039306/nv...,Dog,Dog,Dachshund,NaN,False,False,NaN,NaN,NaN,Young,Male,Small,Long,True,False,NaN,False,True,True,True,True,Theo,adoptable,2019-09-20T06:48:30+0000,Henderson,NV,89052,US,89009,2019-09-20,Dog,Theo is a friendly dachshund mix who gets alon...

In [8]:
dog_desc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58180 entries, 0 to 58179
Data columns (total 36 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            58180 non-null  int64
 1   id               58180 non-null  int64
 2   org_id           58180 non-null  object
 3   url              58180 non-null  object
 4   type.x           58180 non-null  object
 5   species          58180 non-null  object
 6   breed_primary    58180 non-null  object
 7   breed_secondary  20821 non-null  object
 8   breed_mixed      58180 non-null  bool
 9   breed_unknown    58180 non-null  bool
 10  color_primary    26134 non-null  object
 11  color_secondary  12059 non-null  object
 12  color_tertiary   1217 non-null   object
 13  age              58180 non-null  object
 14  sex              58180 non-null  object
 15  size             58180 non-null  object
 16  coat             27185 non-null  object
 17  fixed            58180 non-null  bool
 18  house_trained    58180 non-null  bool
 19  declawed         0 non-null      float64
 20  special_needs    58180 non-null  bool
 21  shots_current    58180 non-null  bool
 22  env_children     28027 non-null  object
 23  env_dogs         34669 non-null  object
 24  env_cats         19352 non-null  object
 25  name             58180 non-null  object
 26  status           58180 non-null  object
 27  posted           58180 non-null  object
 28  contact_city     58180 non-null  object
 29  contact_state    58180 non-null  object
 30  contact_zip      58168 non-null  object
 31  contact_country  58180 non-null  object
 32  stateQ           58180 non-null  object
 33  accessed         58147 non-null  object
 34  type.y           57540 non-null  object
 35  description      49475 non-null  object
dtypes: bool(6), float64(1), int64(2), object(27)
memory usage: 13.6+ MB

In [9]:
def missing_vals(df): 
    for i in df : 
        print(f"{i}:{df[i].isnull().sum()} out of {len(df[i])}")
        
missing_vals(dog_desc_df)

index:0 out of 58180
id:0 out of 58180
org_id:0 out of 58180
url:0 out of 58180
type.x:0 out of 58180
species:0 out of 58180
breed_primary:0 out of 58180
breed_secondary:37359 out of 58180
breed_mixed:0 out of 58180
breed_unknown:0 out of 58180
color_primary:32046 out of 58180
color_secondary:46121 out of 58180
color_tertiary:56963 out of 58180
age:0 out of 58180
sex:0 out of 58180
size:0 out of 58180
coat:30995 out of 58180
fixed:0 out of 58180
house_trained:0 out of 58180
declawed:58180 out of 58180
special_needs:0 out of 58180
shots_current:0 out of 58180
env_children:30153 out of 58180
env_dogs:23511 out of 58180
env_cats:38828 out of 58180
name:0 out of 58180
status:0 out of 58180
posted:0 out of 58180
contact_city:0 out of 58180
contact_state:0 out of 58180
contact_zip:12 out of 58180
contact_country:0 out of 58180
stateQ:0 out of 58180
accessed:33 out of 58180
type.y:640 out of 58180
description:8705 out of 58180

In [10]:
def cat_cols(df) : 
    o = (df.dtypes == 'object')
    object_cols = o[o].index 
    return object_cols

object_cols = cat_cols(dog_desc_df)
object_cols

Index(['org_id', 'url', 'type.x', 'species', 'breed_primary',
       'breed_secondary', 'color_primary', 'color_secondary', 'color_tertiary',
       'age', 'sex', 'size', 'coat', 'env_children', 'env_dogs', 'env_cats',
       'name', 'status', 'posted', 'contact_city', 'contact_state',
       'contact_zip', 'contact_country', 'stateQ', 'accessed', 'type.y',
       'description'],
      dtype='object')

### Seeing which states have the most imports of dogs and what breeds/types those are ?

In [11]:
count_of_dogs = 0
contact_country_dict = {}
for i in dog_desc_df['contact_country']:
    if i =='US' : 
        contact_country_dict['breed'] = dog_desc_df['breed_primary']
        contact_country_dict['type.x'] = dog_desc_df['type.x']
        contact_country_dict['contact_state'] = dog_desc_df['contact_state']
        count_of_dogs += 1

In [12]:
contact_country_df = pd.DataFrame(contact_country_dict)
contact_country_df.head()

                            breed type.x contact_state
0  American Staffordshire Terrier    Dog            NV
1                Pit Bull Terrier    Dog            NV
2                        Shepherd    Dog            NV
3             German Shepherd Dog    Dog            NV
4                       Dachshund    Dog            NV

In [13]:
contact_country_df.to_csv('contact_country.csv')

In [17]:
df1_dict = {}
count = 0
for i in dog_desc_df['status']:
    if i =='adoptable' : 
        df1_dict['breed'] = dog_desc_df['breed_primary']
        df1_dict['type.x'] = dog_desc_df['type.x']
        count += 1 


adopted_dogs_in_us = pd.DataFrame(df1_dict)

adopted_dogs_in_us.head()

                            breed type.x
0  American Staffordshire Terrier    Dog
1                Pit Bull Terrier    Dog
2                        Shepherd    Dog
3             German Shepherd Dog    Dog
4                       Dachshund    Dog

In [35]:
# remove the data where the state name is numbers
contact_country_df = contact_country_df[~contact_country_df['contact_state'].str.isnumeric()]

In [41]:

state_lookup = {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California',
    'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'FL': 'Florida', 'GA': 'Georgia',
    'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa',
    'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland',
    'MA': 'Massachusetts', 'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi', 'MO': 'Missouri',
    'MT': 'Montana', 'NE': 'Nebraska', 'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey',
    'NM': 'New Mexico', 'NY': 'New York', 'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio',
    'OK': 'Oklahoma', 'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina',
    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont',
    'VA': 'Virginia', 'WA': 'Washington', 'WV': 'West Virginia', 'WI': 'Wisconsin', 'WY': 'Wyoming',
    # Territories
    'AS': 'American Samoa', 'DC': 'District of Columbia', 'FM': 'Federated States of Micronesia',
    'GU': 'Guam', 'MH': 'Marshall Islands', 'MP': 'Northern Mariana Islands', 'PW': 'Palau',
    'PR': 'Puerto Rico', 'VI': 'Virgin Islands'
}


df_full = pd.read_csv('/Users/linfangqing/Desktop/dog_adopt/state_shelters.csv')
df_full['State_Full'] = df_full['state']
contact_country_df['State_Full'] = contact_country_df['contact_state'].map(state_lookup)

# Check for any states that didn't get a match in the lookup
unmatched_states = contact_country_df['State_Full'].isnull()
if unmatched_states.any():
    print("Some states didn't match the lookup table:")
    print(contact_country_df.loc[unmatched_states, 'contact_state'])
print(unmatched_states.sum())

# remove the unmatched states
combined_df = contact_country_df[~unmatched_states]

combined_df = contact_country_df.merge(df_full, on='State_Full', how='inner')

# Check for any missing values that may indicate unmatched states
if combined_df.isnull().any().any():
    print("There are unmatched or missing values in the combined dataframe.")

combined_df.to_csv("joined_data.csv")

Some states didn't match the lookup table:
36151    QC
36173    QC
36222    NB
36223    NB
42621    QC
42622    QC
42639    QC
42640    QC
42761    QC
42762    QC
42763    QC
42773    QC
42801    QC
42819    QC
55537    QC
55575    QC
Name: contact_state, dtype: object
16