In [56]:
import pandas as pd

In [57]:
dog_all=pd.read_csv("best_in_show.csv")

In [58]:
dog_all.head()

,Dog breed,Unnamed: 1,category,Unnamed: 3,datadog score,POPULARITY IN US,POPULARITY IN US.1,"LIFETIME COST, $",5 LIFETIME COST,Unnamed: 9,...,Unnamed: 59,"Other regular costs, total per lifetime, $","total per year, $","total, per year, £","toys, presents, treats, per year, £","pet sitters, per year, £","grooming, per year, £","vet fees per year, £","kennels per year, £","one offs, $"
0,Additional info,NaN,American Kennel Club group,NaN,NaN,"1- 173, 1 = most poular, US. American Kennel C...",ranking within breeds with full data only,NaN,"in descending rank (higher score = better), n...",NaN,...,NaN,"if no average lifespan data, then 'no data'",converted to US $ using Google Finance,NaN,averaged across all dog breeds. pet food exclu...,NaN,NaN,NaN,NaN,"Initial outlay: leash, collar, ID tag; food di..."
1,Border Collie,NaN,herding,NaN,3.64,45,39,"$20,143",48%,NaN,...,NaN,"13,095","1,046",784.0,121,126.0,244.0,177.0,116.0,200
2,Border Terrier,NaN,terrier,NaN,3.61,80,61,"$22,638",14%,NaN,...,NaN,"14,643","1,046",784.0,121,126.0,244.0,177.0,116.0,200
3,Brittany,NaN,sporting,NaN,3.54,30,30,"$22,589",16%,NaN,...,NaN,"13,514","1,046",784.0,121,126.0,244.0,177.0,116.0,200
4,Cairn Terrier,NaN,terrier,NaN,3.53,59,48,"$21,992",22%,NaN,...,NaN,"14,476","1,046",784.0,121,126.0,244.0,177.0,116.0,200

In [59]:
dog_all["Breed"]=dog_all["Dog breed"]

In [60]:
dog_height=pd.read_csv("AKC Breed Info.csv")

In [61]:
dog_height.head()

,index,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs
0,0,Akita,26,28,80,120
1,1,Anatolian Sheepdog,27,29,100,150
2,2,Bernese Mountain Dog,23,27,85,110
3,3,Bloodhound,24,26,80,120
4,4,Borzoi,26,28,70,100

In [62]:
dog_inte=pd.read_csv("dog_intelligence.csv")

In [63]:
dog_inte.head()

   index              Breed  Classification obey  reps_lower  reps_upper
0      0      Border Collie  Brightest Dogs  95%           1           4
1      1             Poodle  Brightest Dogs  95%           1           4
2      2    German Shepherd  Brightest Dogs  95%           1           4
3      3   Golden Retriever  Brightest Dogs  95%           1           4
4      4  Doberman Pinscher  Brightest Dogs  95%           1           4

In [64]:
dog_merge=pd.merge(dog_all,dog_height,on='Breed')

In [65]:
dog_merge=pd.merge(dog_merge,dog_inte,on='Breed')

In [66]:
dog_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 80 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Dog breed                                                         105 non-null    object
 1   Unnamed: 1                                                        0 non-null      float64
 2   category                                                          105 non-null    object
 3   Unnamed: 3                                                        0 non-null      float64
 4   datadog score                                                     70 non-null     float64
 5   POPULARITY IN US                                                  105 non-null    object
 6   POPULARITY IN US.1                                                70 non-null     object
 7   LIFETIME COST, $                                                  105 non-null    object
 8   5 LIFETIME COST                                                   70 non-null     object
 9   Unnamed: 9                                                        0 non-null      float64
 10  1 INTELLIGENCE (TRAINABILITY) ranking                             105 non-null    object
 11  INTELLIGENCE (TRAINABILITY) ranking                               70 non-null     object
 12  2 LONGEVITY                                                       105 non-null    object
 13  LONGEVITY                                                         70 non-null     object
 14  3 NO. OF GENETIC AILMENTS                                         105 non-null    object
 15  GENETIC AILMENTS                                                  70 non-null     object
 16  4a average purchase price, US$                                    105 non-null    object
 17  average purchase price, US$                                       70 non-null     object
 18  4b food costs per year, US$                                       70 non-null     object
 19  food costs per year, US$                                          70 non-null     object
 20  5a grooming required                                              105 non-null    object
 21  grooming required                                                 70 non-null     object
 22  5b suitability for children                                       105 non-null    object
 23  suitability for children                                          70 non-null     object
 24  Unnamed: 24                                                       0 non-null      float64
 25  ULTIMATE TOP DOG MEGA SCORE (with kids)                           70 non-null     object
 26  ULTIMATE TOP DATA DOG MEGA RANKING - without kids                 70 non-null     float64
 27  ULTIMATE TOP DATA DOG MEGA RANKING - with kids                    70 non-null     float64
 28  ULTIMATE TOP DOG MEGA SCORE                                       70 non-null     object
 29  POPULAR RATING                                                    70 non-null     object
 30  Unnamed: 30                                                       0 non-null      float64
 31  size category                                                     105 non-null    object
 32  weight (kg)                                                       105 non-null    object
 33  weight (lbs)                                                      105 non-null    object
 34  shoulder height (cm)                                              105 non-null    object
 35  shoulder height (in)                                              105 non-null    object
 36  Unnamed: 36                                                       0 non-null      float64
 37  note                                                              19 non-null     object
 38  intelligence category                                             105 non-null    object
 39  repetitions to understand new commands                            105 non-null    object
 40  obey first command (% of time)                                    105 non-null    object
 41  longevity sample size - survey sample size                        105 non-null    object
 42  GENETIC DISEASES - congenital ailments: summary / areas affected  105 non-null    object
 43  congenital ailments: summary / areas affected                     105 non-null    object
 44  exclude?                                                          0 non-null      object
 45  most abandoned?                                                   0 non-null      object
 46  Unnamed: 46                                                       0 non-null      float64
 47  4 LIFETIME COST, $                                                105 non-null    object
 48  4 LIFETIME COST                                                   70 non-null     object
 49  average purchase price (US $)                                     105 non-null    object
 50  price bracket                                                     105 non-null    object
 51  lowest (US$)                                                      105 non-null    object
 52  highest (US$)                                                     105 non-null    object
 53  food per week, average, £                                         105 non-null    object
 54  min, £                                                            105 non-null    object
 55  max, £                                                            105 non-null    object
 56  food per week, $                                                  105 non-null    object
 57  food per year, $                                                  70 non-null     object
 58  food per lifetime, $                                              105 non-null    object
 59  Unnamed: 59                                                       0 non-null      float64
 60  Other regular costs, total per lifetime, $                        105 non-null    object
 61  total  per year, $                                                105 non-null    object
 62  total, per year, £                                                105 non-null    float64
 63  toys, presents, treats, per year, £                               105 non-null    object
 64  pet sitters, per year, £                                          105 non-null    float64
 65  grooming, per year, £                                             105 non-null    float64
 66  vet fees per year, £                                              105 non-null    float64
 67  kennels per year, £                                               105 non-null    float64
 68  one offs, $                                                       105 non-null    object
 69  Breed                                                             105 non-null    object
 70  index_x                                                           105 non-null    int64
 71  height_low_inches                                                 105 non-null    object
 72  height_high_inches                                                105 non-null    object
 73  weight_low_lbs                                                    105 non-null    object
 74  weight_high_lbs                                                   105 non-null    object
 75  index_y                                                           105 non-null    int64
 76  Classification                                                    105 non-null    object
 77  obey                                                              96 non-null     object
 78  reps_lower                                                        105 non-null    int64
 79  reps_upper                                                        105 non-null    int64
dtypes: float64(16), int64(4), object(60)
memory usage: 65.8+ KB

In [67]:
dog_merge.columns

Index(['Dog breed', 'Unnamed: 1', 'category', 'Unnamed: 3', 'datadog score',
       'POPULARITY IN US', 'POPULARITY IN US.1', 'LIFETIME COST, $',
       '5 LIFETIME COST', 'Unnamed: 9',
       '1 INTELLIGENCE (TRAINABILITY) ranking',
       'INTELLIGENCE (TRAINABILITY) ranking', '2 LONGEVITY', 'LONGEVITY',
       '3 NO. OF GENETIC AILMENTS', 'GENETIC AILMENTS',
       '4a average purchase price, US$', 'average purchase price, US$',
       '4b food costs per year, US$', 'food costs per year, US$',
       '5a grooming required ', 'grooming required ',
       '5b suitability for children ', 'suitability for children ',
       'Unnamed: 24', 'ULTIMATE TOP DOG MEGA SCORE (with kids)',
       'ULTIMATE TOP DATA DOG MEGA RANKING - without kids',
       'ULTIMATE TOP DATA DOG MEGA RANKING - with kids',
       'ULTIMATE TOP DOG MEGA SCORE', 'POPULAR RATING', 'Unnamed: 30',
       'size category', 'weight (kg)', 'weight (lbs)', 'shoulder height (cm)',
       'shoulder height (in)', 'Unnamed: 36', 'note', 'intelligence category',
       'repetitions to understand new commands',
       'obey first command (% of time)',
       'longevity sample size - survey sample size',
       'GENETIC DISEASES - congenital ailments: summary / areas affected',
       'congenital ailments: summary / areas affected', 'exclude?',
       'most abandoned?', 'Unnamed: 46', '4 LIFETIME COST, $',
       '4 LIFETIME COST', 'average purchase price (US $)', 'price bracket',
       'lowest (US$)', 'highest (US$)', 'food per week, average, £', 'min, £',
       'max, £', 'food per week, $', 'food per year, $',
       'food per lifetime, $', 'Unnamed: 59',
       'Other regular costs, total per lifetime, $', 'total  per year, $',
       'total, per year, £', 'toys, presents, treats, per year, £',
       'pet sitters, per year, £', 'grooming, per year, £',
       'vet fees per year, £', 'kennels per year, £', 'one offs, $', 'Breed',
       'index_x', 'height_low_inches', 'height_high_inches', 'weight_low_lbs',
       'weight_high_lbs', 'index_y', 'Classification', 'obey', 'reps_lower',
       'reps_upper'],
      dtype='object')

In [68]:
dog_merge["height_high_inches"] = pd.to_numeric(dog_merge["height_high_inches"], errors='coerce')
dog_merge["height_low_inches"] = pd.to_numeric(dog_merge["height_low_inches"], errors='coerce')

# Calculate average height
dog_merge['Average_Height'] = (dog_merge["height_high_inches"] + dog_merge["height_low_inches"]) / 2

In [69]:
# Convert non-numeric values to NaN
dog_merge["weight_high_lbs"] = pd.to_numeric(dog_merge["weight_high_lbs"], errors='coerce')
dog_merge["weight_low_lbs"] = pd.to_numeric(dog_merge["weight_low_lbs"], errors='coerce')

# Calculate average weight
dog_merge['Average_Weight'] = (dog_merge["weight_high_lbs"] + dog_merge["weight_low_lbs"]) / 2

In [70]:
dog_merge.head()

,Dog breed,Unnamed: 1,category,Unnamed: 3,datadog score,POPULARITY IN US,POPULARITY IN US.1,"LIFETIME COST, $",5 LIFETIME COST,Unnamed: 9,...,height_high_inches,weight_low_lbs,weight_high_lbs,index_y,Classification,obey,reps_lower,reps_upper,Average_Height,Average_Weight
0,Border Collie,NaN,herding,NaN,3.64,45,39,"$20,143",48%,NaN,...,21.0,40.0,40.0,0,Brightest Dogs,95%,1,4,20.0,40.0
1,Border Terrier,NaN,terrier,NaN,3.61,80,61,"$22,638",14%,NaN,...,15.0,12.0,15.0,38,Above Average Working Dogs,70%,16,25,13.5,13.5
2,Brittany,NaN,sporting,NaN,3.54,30,30,"$22,589",16%,NaN,...,21.0,30.0,40.0,22,Excellent Working Dogs,85%,5,15,19.0,35.0
3,Cairn Terrier,NaN,terrier,NaN,3.53,59,48,"$21,992",22%,NaN,...,10.0,14.0,14.0,49,Above Average Working Dogs,70%,16,25,9.5,14.0
4,Welsh Springer Spaniel,NaN,sporting,NaN,3.34,130,81,"$20,224",47%,NaN,...,19.0,35.0,45.0,40,Above Average Working Dogs,70%,16,25,17.5,40.0

In [71]:
dog_filtered=dog_merge[['Breed','datadog score','POPULARITY IN US.1','LONGEVITY','LIFETIME COST, $','Average_Height','Average_Weight','obey','intelligence category']]

In [72]:
dog_filtered

,Breed,datadog score,POPULARITY IN US.1,LONGEVITY,"LIFETIME COST, $",Average_Height,Average_Weight,obey,intelligence category
0,Border Collie,3.64,39,79%,"$20,143",20.0,40.0,95%,Brightest
1,Border Terrier,3.61,61,98%,"$22,638",13.5,13.5,70%,Above average
2,Brittany,3.54,30,89%,"$22,589",19.0,35.0,85%,Excellent
3,Cairn Terrier,3.53,48,95%,"$21,992",9.5,14.0,70%,Above average
4,Welsh Springer Spaniel,3.34,81,77%,"$20,224",17.5,40.0,70%,Above average
...,...,...,...,...,...,...,...,...,...
100,Standard Schnauzer,NaN,NaN,NaN,no data,18.0,33.0,85%,Excellent
101,Vizsla,NaN,NaN,NaN,no data,57.0,23.5,85%,Excellent
102,Weimaraner,NaN,NaN,NaN,no data,26.0,77.5,85%,Excellent
103,Welsh Terrier,NaN,NaN,NaN,no data,15.0,20.5,50%,Average
104,Wirehaired Pointing Griffon,NaN,NaN,NaN,no data,22.0,52.5,50%,Average

In [73]:
dog_filtered_cleaned=dog_filtered.dropna()

In [74]:
dog_filtered_cleaned

,Breed,datadog score,POPULARITY IN US.1,LONGEVITY,"LIFETIME COST, $",Average_Height,Average_Weight,obey,intelligence category
0,Border Collie,3.64,39,79%,"$20,143",20.0,40.0,95%,Brightest
1,Border Terrier,3.61,61,98%,"$22,638",13.5,13.5,70%,Above average
2,Brittany,3.54,30,89%,"$22,589",19.0,35.0,85%,Excellent
3,Cairn Terrier,3.53,48,95%,"$21,992",9.5,14.0,70%,Above average
4,Welsh Springer Spaniel,3.34,81,77%,"$20,224",17.5,40.0,70%,Above average
5,Papillon,3.26,33,90%,"$21,001",9.5,7.5,95%,Brightest
6,Australian Cattle Dog,3.25,49,55%,"$20,395",18.5,40.0,95%,Brightest
7,Siberian Husky,3.22,16,83%,"$22,049",21.5,50.0,50%,Average
8,Affenpinscher,3.20,84,47%,"$18,333",10.5,10.0,70%,Above average
9,Dachshund,3.19,9,85%,"$20,113",8.5,24.0,50%,Average
10,Chihuahua,3.15,14,100%,"$26,250",7.5,3.5,30%,Fair
11,Australian Terrier,3.11,77,40%,"$17,892",10.0,12.0,70%,Above average
12,Whippet,3.11,46,87%,"$20,976",20.0,28.5,50%,Average
13,English Springer Spaniel,3.09,29,82%,"$21,946",20.0,50.0,85%,Excellent
14,West Highland White Terrier,3.08,32,86%,"$20,490",11.0,14.0,50%,Average
15,Bedlington Terrier,3.07,83,93%,"$22,107",15.5,20.5,50%,Average
16,Bichon Frise,3.03,34,68%,"$19,735",10.5,14.0,50%,Average
17,German Shorthaired Pointer,3.03,15,49%,"$25,842",23.5,65.0,85%,Excellent
18,Pointer,3.03,74,75%,"$24,445",22.5,55.0,50%,Average
19,Tibetan Spaniel,3.02,73,99%,"$25,549",10.0,12.0,50%,Average
20,Labrador Retriever,2.97,1,63%,"$21,299",22.5,67.5,95%,Brightest
21,Maltese,2.93,23,69%,"$19,084",9.0,5.0,30%,Fair
22,Pomeranian,2.93,17,23%,"$15,792",12.0,5.0,85%,Excellent
24,Australian Shepherd,2.91,24,71%,"$21,458",20.5,50.0,50%,Average
25,Yorkshire Terrier,2.85,5,84%,"$20,701",8.0,5.0,70%,Above average
26,Irish Setter,2.84,56,53%,"$20,323",26.0,65.0,70%,Above average
27,Pharaoh Hound,2.81,86,57%,"$21,047",23.0,50.0,70%,Above average
28,Golden Retriever,2.80,4,63%,"$21,447",22.5,65.0,95%,Brightest
29,Samoyed,2.80,55,76%,"$25,352",21.5,57.5,70%,Above average
31,Chesapeake Bay Retriever,2.78,40,22%,"$16,697",23.5,65.0,70%,Above average
32,Tibetan Terrier,2.75,64,74%,"$20,336",15.5,25.0,30%,Fair
33,Gordon Setter,2.73,69,41%,"$19,605",25.0,62.5,70%,Above average
34,English Setter,2.72,65,52%,"$20,312",25.0,62.5,70%,Above average
35,Pug,2.72,26,39%,"$18,527",10.5,18.0,30%,Fair
36,Briard,2.71,79,43%,"$19,673",25.0,75.0,70%,Above average
37,Boston Terrier,2.61,22,38%,"$17,741",14.5,20.0,50%,Average
38,Doberman Pinscher,2.59,13,32%,"$18,397",27.0,80.0,95%,Brightest
39,Cavalier King Charles Spaniel,2.57,21,46%,"$18,639",12.5,17.5,50%,Average
40,Dalmatian,2.57,57,45%,"$19,886",21.0,57.5,70%,Above average
43,Italian Greyhound,2.49,53,28%,"$16,463",13.5,8.0,30%,Fair
44,Staffordshire Bull Terrier,2.48,58,66%,"$21,650",15.0,26.0,50%,Average
45,Clumber Spaniel,2.44,82,25%,"$18,084",19.5,50.0,70%,Above average
46,Dandie Dinmont Terrier,2.42,87,67%,"$21,633",21.0,9.5,30%,Fair
47,Saluki,2.41,75,61%,"$24,866",25.5,52.5,50%,Average
48,Giant Schnauzer,2.38,70,25%,"$26,686",26.5,72.5,70%,Above average
49,Greyhound,2.29,85,20%,"$15,819",28.5,65.0,50%,Average
50,Scottish Terrier,2.27,45,37%,"$17,525",11.0,20.0,30%,Fair
51,Rottweiler,2.24,10,17%,"$18,886",24.5,100.0,95%,Brightest
52,Kerry Blue Terrier,2.13,78,21%,"$17,240",19.0,37.5,70%,Above average
54,Newfoundland,2.07,37,18%,"$19,351",27.0,125.0,70%,Above average
55,Akita,1.95,41,30%,"$20,994",27.0,100.0,50%,Average
56,Rhodesian Ridgeback,1.91,38,16%,"$16,530",25.5,77.5,50%,Average
57,French Bulldog,1.90,18,11%,"$17,266",11.5,22.5,30%,Fair
59,Bernese Mountain Dog,1.85,31,7%,"$16,099",25.0,97.5,85%,Excellent
60,Bull Terrier,1.85,44,31%,"$18,490",21.5,60.0,30%,Fair
61,Boxer,1.83,7,10%,"$15,746",23.0,67.5,50%,Average
65,Irish Wolfhound,1.66,60,5%,"$18,435",31.5,120.0,50%,Average
66,Bullmastiff,1.64,35,8%,"$13,936",26.0,115.0,30%,Fair
68,Great Dane,1.53,19,6%,"$14,662",32.0,140.0,50%,Average
69,Saint Bernard,1.42,43,9%,"$20,022",26.5,150.0,30%,Fair

In [75]:
intell=dog_filtered_cleaned['intelligence category']

In [76]:
intell.unique()

array(['Brightest', 'Above average', 'Excellent', 'Average', 'Fair'],
      dtype=object)

In [77]:
mapping = {'Brightest': 5, 'Excellent': 4, 'Above average': 3, 'Average': 2, 'Fair': 1}

# Replace the categories with numbers
dog_filtered_cleaned['intelligence category'] = dog_filtered_cleaned['intelligence category'].replace(mapping)

# Display the DataFrame with replaced values

/var/folders/xn/mx6s6c89295c4697_q6fwb1h0000gn/T/ipykernel_62464/2192746314.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dog_filtered_cleaned['intelligence category'] = dog_filtered_cleaned['intelligence category'].replace(mapping)
/var/folders/xn/mx6s6c89295c4697_q6fwb1h0000gn/T/ipykernel_62464/2192746314.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dog_filtered_cleaned['intelligence category'] = dog_filtered_cleaned['intelligence category'].replace(mapping)

In [78]:
dog_filtered_cleaned = dog_filtered_cleaned.rename(columns={'intelligence category': 'Intelligence'})
dog_filtered_cleaned = dog_filtered_cleaned.rename(columns={'LIFETIME COST, $': 'Lifetime_Cost'})
dog_filtered_cleaned = dog_filtered_cleaned.rename(columns={'POPULARITY IN US.1': 'Popularity'})
dog_filtered_cleaned['Lifetime_Cost'] = dog_filtered_cleaned['Lifetime_Cost'].str.replace('$', '')

In [79]:
dog_filtered_cleaned

,Breed,datadog score,Popularity,LONGEVITY,Lifetime_Cost,Average_Height,Average_Weight,obey,Intelligence
0,Border Collie,3.64,39,79%,"20,143",20.0,40.0,95%,5
1,Border Terrier,3.61,61,98%,"22,638",13.5,13.5,70%,3
2,Brittany,3.54,30,89%,"22,589",19.0,35.0,85%,4
3,Cairn Terrier,3.53,48,95%,"21,992",9.5,14.0,70%,3
4,Welsh Springer Spaniel,3.34,81,77%,"20,224",17.5,40.0,70%,3
5,Papillon,3.26,33,90%,"21,001",9.5,7.5,95%,5
6,Australian Cattle Dog,3.25,49,55%,"20,395",18.5,40.0,95%,5
7,Siberian Husky,3.22,16,83%,"22,049",21.5,50.0,50%,2
8,Affenpinscher,3.20,84,47%,"18,333",10.5,10.0,70%,3
9,Dachshund,3.19,9,85%,"20,113",8.5,24.0,50%,2
10,Chihuahua,3.15,14,100%,"26,250",7.5,3.5,30%,1
11,Australian Terrier,3.11,77,40%,"17,892",10.0,12.0,70%,3
12,Whippet,3.11,46,87%,"20,976",20.0,28.5,50%,2
13,English Springer Spaniel,3.09,29,82%,"21,946",20.0,50.0,85%,4
14,West Highland White Terrier,3.08,32,86%,"20,490",11.0,14.0,50%,2
15,Bedlington Terrier,3.07,83,93%,"22,107",15.5,20.5,50%,2
16,Bichon Frise,3.03,34,68%,"19,735",10.5,14.0,50%,2
17,German Shorthaired Pointer,3.03,15,49%,"25,842",23.5,65.0,85%,4
18,Pointer,3.03,74,75%,"24,445",22.5,55.0,50%,2
19,Tibetan Spaniel,3.02,73,99%,"25,549",10.0,12.0,50%,2
20,Labrador Retriever,2.97,1,63%,"21,299",22.5,67.5,95%,5
21,Maltese,2.93,23,69%,"19,084",9.0,5.0,30%,1
22,Pomeranian,2.93,17,23%,"15,792",12.0,5.0,85%,4
24,Australian Shepherd,2.91,24,71%,"21,458",20.5,50.0,50%,2
25,Yorkshire Terrier,2.85,5,84%,"20,701",8.0,5.0,70%,3
26,Irish Setter,2.84,56,53%,"20,323",26.0,65.0,70%,3
27,Pharaoh Hound,2.81,86,57%,"21,047",23.0,50.0,70%,3
28,Golden Retriever,2.80,4,63%,"21,447",22.5,65.0,95%,5
29,Samoyed,2.80,55,76%,"25,352",21.5,57.5,70%,3
31,Chesapeake Bay Retriever,2.78,40,22%,"16,697",23.5,65.0,70%,3
32,Tibetan Terrier,2.75,64,74%,"20,336",15.5,25.0,30%,1
33,Gordon Setter,2.73,69,41%,"19,605",25.0,62.5,70%,3
34,English Setter,2.72,65,52%,"20,312",25.0,62.5,70%,3
35,Pug,2.72,26,39%,"18,527",10.5,18.0,30%,1
36,Briard,2.71,79,43%,"19,673",25.0,75.0,70%,3
37,Boston Terrier,2.61,22,38%,"17,741",14.5,20.0,50%,2
38,Doberman Pinscher,2.59,13,32%,"18,397",27.0,80.0,95%,5
39,Cavalier King Charles Spaniel,2.57,21,46%,"18,639",12.5,17.5,50%,2
40,Dalmatian,2.57,57,45%,"19,886",21.0,57.5,70%,3
43,Italian Greyhound,2.49,53,28%,"16,463",13.5,8.0,30%,1
44,Staffordshire Bull Terrier,2.48,58,66%,"21,650",15.0,26.0,50%,2
45,Clumber Spaniel,2.44,82,25%,"18,084",19.5,50.0,70%,3
46,Dandie Dinmont Terrier,2.42,87,67%,"21,633",21.0,9.5,30%,1
47,Saluki,2.41,75,61%,"24,866",25.5,52.5,50%,2
48,Giant Schnauzer,2.38,70,25%,"26,686",26.5,72.5,70%,3
49,Greyhound,2.29,85,20%,"15,819",28.5,65.0,50%,2
50,Scottish Terrier,2.27,45,37%,"17,525",11.0,20.0,30%,1
51,Rottweiler,2.24,10,17%,"18,886",24.5,100.0,95%,5
52,Kerry Blue Terrier,2.13,78,21%,"17,240",19.0,37.5,70%,3
54,Newfoundland,2.07,37,18%,"19,351",27.0,125.0,70%,3
55,Akita,1.95,41,30%,"20,994",27.0,100.0,50%,2
56,Rhodesian Ridgeback,1.91,38,16%,"16,530",25.5,77.5,50%,2
57,French Bulldog,1.90,18,11%,"17,266",11.5,22.5,30%,1
59,Bernese Mountain Dog,1.85,31,7%,"16,099",25.0,97.5,85%,4
60,Bull Terrier,1.85,44,31%,"18,490",21.5,60.0,30%,1
61,Boxer,1.83,7,10%,"15,746",23.0,67.5,50%,2
65,Irish Wolfhound,1.66,60,5%,"18,435",31.5,120.0,50%,2
66,Bullmastiff,1.64,35,8%,"13,936",26.0,115.0,30%,1
68,Great Dane,1.53,19,6%,"14,662",32.0,140.0,50%,2
69,Saint Bernard,1.42,43,9%,"20,022",26.5,150.0,30%,1

In [80]:
dog_filtered_cleaned.to_csv('dog_filtered_cleaned.csv', index=False)

In [81]:
# Convert 'LONGEVITY' column to numeric values
dog_filtered_cleaned['LONGEVITY'] = dog_filtered_cleaned['LONGEVITY'].str.replace('%', '')
dog_filtered_cleaned['LONGEVITY'] = dog_filtered_cleaned['LONGEVITY'].astype(float) / 100



# Min-Max scaling
df_normalized = dog_filtered_cleaned.copy()
for column in df_normalized.columns:
    if column != 'Breed':
        if df_normalized[column].dtype != 'object':
            df_normalized[column] = (df_normalized[column] - df_normalized[column].min()) / (df_normalized[column].max() - df_normalized[column].min())

# Display the normalized DataFrame
df_normalized.head()

,Breed,datadog score,Popularity,LONGEVITY,Lifetime_Cost,Average_Height,Average_Weight,obey,Intelligence
0,Border Collie,1.000000,39,0.778947,"20,143",0.510204,0.249147,95%,1.00
1,Border Terrier,0.986486,61,0.978947,"22,638",0.244898,0.068259,70%,0.50
2,Brittany,0.954955,30,0.884211,"22,589",0.469388,0.215017,85%,0.75
3,Cairn Terrier,0.950450,48,0.947368,"21,992",0.081633,0.071672,70%,0.50
4,Welsh Springer Spaniel,0.864865,81,0.757895,"20,224",0.408163,0.249147,70%,0.50